#!/bin/bash

set -eu

. /var/vcap/jobs/airlog/airlog.env

echo $$ > /var/vcap/sys/run/airlog/pid

cd /var/vcap/packages/airlog

exec ./bin/airlog \
  1>> /var/vcap/sys/log/airlog/stdout.log \
  2>> /var/vcap/sys/log/airlog/stderr.log
